package com.machine.view;

import com.machine.factory.ModuloConexao;
import com.machine.model.FormataMoeda;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Double.parseDouble;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class FrameMachine extends javax.swing.JFrame {

    /**
     * Classe
     *
     * @author Juliano
     * @version 1.1
     */
    Connection conexao;
    PreparedStatement pst;
    ResultSet rs;

    public FrameMachine() {
        initComponents();
        fotoNota2();
        fotoNota5();
        fotoNota10();
        conexao = ModuloConexao.conectar();
        CarregaLabels();
        CarregaDinheiro(0.00);

    }
     public String preco;
    public double dinheiro = 0.00, troco = 0;
    public double valor[] = new double[9];
    JLabel[] Fotoproduto = new JLabel[9];
    JLabel[] Precoproduto = new JLabel[9];
    JLabel[] botao = new JLabel[9];
    

        
    FormataMoeda formatador = new FormataMoeda();
    

    private void CarregaLabels() {
        Fotoproduto = new JLabel[]{lblQuadro1, lblQuadro2, lblQuadro3, lblQuadro4, lblQuadro5, lblQuadro6, lblQuadro7, lblQuadro8, lblQuadro9};
        Precoproduto = new JLabel[]{lblValor1, lblValor2, lblValor3, lblValor4, lblValor5, lblValor6, lblValor7, lblValor8, lblValor9};
        botao = new JLabel[]{lblNmr1,lblNmr2,lblNmr3,lblNmr4,lblNmr5,lblNmr6,lblNmr7,lblNmr8,lblNmr9};
        CarregaDoces();
    }

    private void CarregaDoces() {
        int i = 0;
        String sql = "select * from tb01_produto";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                if(rs.getInt("tb01_qtde")>0){
                Image img = Toolkit.getDefaultToolkit().createImage(rs.getBytes("tb01_foto"));
                ImageIcon foto = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(Fotoproduto[i].getWidth(), Fotoproduto[i].getHeight(), Image.SCALE_DEFAULT));
                Fotoproduto[i].setIcon(foto);
                valor[i] = parseDouble(rs.getString("tb01_preco"));   
                preco = rs.getString("tb01_preco");
                Precoproduto[i].setText(formatador.ConvMoeda(preco));
                }else{
                botao[i].setEnabled(false);
                }
                i++;
            }
        } catch (SQLException e) {
            System.out.println("Erro" + e);
        }
    }

    private void movimento(final JLabel fig) {
        new Thread() {
            @Override
            public void run() {
                int y = fig.getLocation().y;
                int x = fig.getLocation().x;
                int z = lblQuadroSaida.getLocation().y;

                while (y <= z) {
                    y = y + 1;
                    fig.setLocation(x, y);

                    try {
                        sleep(6);
                    } catch (InterruptedException e) {
                        System.out.println("erro" + e);
                    }
                }
                lblQuadroSaida.setIcon(fig.getIcon());
                fig.setIcon(null);
            }

        }.start();
    }

    private void CarregaDinheiro(double contagem) {
        dinheiro = dinheiro + contagem;
        txtDinheiro.setText(formatador.ConvMoeda(String.valueOf(dinheiro)));
    }

    private void saidaProd() {
        lblTroco.setText(formatador.ConvMoeda(String.valueOf(troco)));
        lblVisor.setText(null);
        txtDinheiro.setText(null);
        dinheiro = 0;
        
    }

    // Restante do código...
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelCenter = new javax.swing.JPanel();
        JPanelMachine = new javax.swing.JPanel();
        JPanelMachineVisor = new javax.swing.JPanel();
        lblVisor = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        lblNmr1 = new javax.swing.JLabel();
        lblNmr2 = new javax.swing.JLabel();
        lblNmr3 = new javax.swing.JLabel();
        lblNmr4 = new javax.swing.JLabel();
        lblNmr5 = new javax.swing.JLabel();
        lblNmr6 = new javax.swing.JLabel();
        lblNmr7 = new javax.swing.JLabel();
        lblNmr8 = new javax.swing.JLabel();
        lblNmr9 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        lblQuadroSaida = new javax.swing.JLabel();
        JPanelQuadro = new javax.swing.JPanel();
        lblQuadro1 = new javax.swing.JLabel();
        lblQuadro2 = new javax.swing.JLabel();
        lblQuadro3 = new javax.swing.JLabel();
        lblQuadro4 = new javax.swing.JLabel();
        lblQuadro5 = new javax.swing.JLabel();
        lblQuadro6 = new javax.swing.JLabel();
        lblQuadro7 = new javax.swing.JLabel();
        lblQuadro8 = new javax.swing.JLabel();
        lblQuadro9 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        lblValor3 = new javax.swing.JLabel();
        lblValor4 = new javax.swing.JLabel();
        lblValor5 = new javax.swing.JLabel();
        lblValor6 = new javax.swing.JLabel();
        lblValor7 = new javax.swing.JLabel();
        lblValor8 = new javax.swing.JLabel();
        lblValor9 = new javax.swing.JLabel();
        lblDinheiro2 = new javax.swing.JLabel();
        lblDinheiro10 = new javax.swing.JLabel();
        lblDinheiro5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Candy - Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        JPanelCenter.setBackground(new java.awt.Color(255, 255, 255));
        JPanelCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelMachine.setBackground(new java.awt.Color(0, 0, 0));
        JPanelMachine.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JPanelMachineVisor.setBackground(new java.awt.Color(255, 255, 255));
        JPanelMachineVisor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblVisor.setBackground(new java.awt.Color(0, 0, 0));
        lblVisor.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblVisor.setText("            VISOR");
        lblVisor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout JPanelMachineVisorLayout = new javax.swing.GroupLayout(JPanelMachineVisor);
        JPanelMachineVisor.setLayout(JPanelMachineVisorLayout);
        JPanelMachineVisorLayout.setHorizontalGroup(
            JPanelMachineVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMachineVisorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPanelMachineVisorLayout.setVerticalGroup(
            JPanelMachineVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMachineVisorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTroco.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(255, 255, 255));
        lblTroco.setText("         TROCO");
        lblTroco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNmr1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr1.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr1.setText("  1");
        lblNmr1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNmr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNmr1MouseClicked(evt);
            }
        });

        lblNmr2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr2.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr2.setText("  2");
        lblNmr2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNmr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNmr2MouseClicked(evt);
            }
        });

        lblNmr3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr3.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr3.setText("  3");
        lblNmr3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNmr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNmr3MouseClicked(evt);
            }
        });

        lblNmr4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr4.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr4.setText("  4");
        lblNmr4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNmr4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNmr4MouseClicked(evt);
            }
        });

        lblNmr5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr5.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr5.setText("  5");
        lblNmr5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNmr5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNmr5MouseClicked(evt);
            }
        });

        lblNmr6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr6.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr6.setText("  6");
        lblNmr6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNmr6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNmr6MouseClicked(evt);
            }
        });

        lblNmr7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr7.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr7.setText("  7");
        lblNmr7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNmr7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNmr7MouseClicked(evt);
            }
        });

        lblNmr8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr8.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr8.setText("  8");
        lblNmr8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNmr8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNmr8MouseClicked(evt);
            }
        });

        lblNmr9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNmr9.setForeground(new java.awt.Color(255, 255, 255));
        lblNmr9.setText("  9");
        lblNmr9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout JPanelMachineLayout = new javax.swing.GroupLayout(JPanelMachine);
        JPanelMachine.setLayout(JPanelMachineLayout);
        JPanelMachineLayout.setHorizontalGroup(
            JPanelMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMachineLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JPanelMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelMachineLayout.createSequentialGroup()
                        .addComponent(lblNmr1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblNmr2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblNmr3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelMachineLayout.createSequentialGroup()
                        .addComponent(lblNmr4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblNmr5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblNmr6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelMachineLayout.createSequentialGroup()
                        .addComponent(lblNmr7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblNmr8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblNmr9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(JPanelMachineVisor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanelMachineLayout.setVerticalGroup(
            JPanelMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMachineLayout.createSequentialGroup()
                .addComponent(JPanelMachineVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(JPanelMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNmr1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNmr2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNmr3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JPanelMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNmr4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNmr5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNmr6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JPanelMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNmr7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNmr8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNmr9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        JPanelCenter.add(JPanelMachine, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        txtDinheiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDinheiro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDinheiro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtDinheiro.setEnabled(false);
        txtDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDinheiroActionPerformed(evt);
            }
        });
        JPanelCenter.add(txtDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 234, 30));

        lblQuadroSaida.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblQuadroSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuadroSaidaMouseClicked(evt);
            }
        });
        JPanelCenter.add(lblQuadroSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 100, 100));

        JPanelQuadro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.setPreferredSize(new java.awt.Dimension(380, 380));
        JPanelQuadro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuadro1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, 100, 100));

        lblQuadro2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 18, 100, 100));

        lblQuadro3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 18, 100, 100));

        lblQuadro4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 136, 100, 100));

        lblQuadro5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 136, 100, 100));

        lblQuadro6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 139, 100, 100));

        lblQuadro7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 257, 100, 100));

        lblQuadro8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 257, 100, 100));

        lblQuadro9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblQuadro9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblQuadro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 257, 100, 100));

        lblValor1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblValor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 116, 100, 20));

        lblValor2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblValor2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 116, 100, 20));

        lblValor3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblValor3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 100, 20));

        lblValor4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblValor4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 236, 100, 20));

        lblValor5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblValor5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 236, 100, 20));

        lblValor6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblValor6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 236, 100, 20));

        lblValor7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblValor7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 356, 100, 20));

        lblValor8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblValor8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 356, 100, 20));

        lblValor9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblValor9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelQuadro.add(lblValor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 356, 100, 20));

        JPanelCenter.add(JPanelQuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 401, 395));

        lblDinheiro2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblDinheiro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDinheiro2MouseClicked(evt);
            }
        });
        JPanelCenter.add(lblDinheiro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 82, 32));

        lblDinheiro10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblDinheiro10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDinheiro10MouseClicked(evt);
            }
        });
        JPanelCenter.add(lblDinheiro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 82, 32));

        lblDinheiro5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblDinheiro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDinheiro5MouseClicked(evt);
            }
        });
        JPanelCenter.add(lblDinheiro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 82, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCenter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated


    }//GEN-LAST:event_formWindowActivated

    private void lblDinheiro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDinheiro2MouseClicked

        CarregaDinheiro(2);


    }//GEN-LAST:event_lblDinheiro2MouseClicked

    private void lblDinheiro5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDinheiro5MouseClicked

        CarregaDinheiro(5);

    }//GEN-LAST:event_lblDinheiro5MouseClicked

    private void lblDinheiro10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDinheiro10MouseClicked

        CarregaDinheiro(10);

    }//GEN-LAST:event_lblDinheiro10MouseClicked

    private void txtDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDinheiroActionPerformed

    }//GEN-LAST:event_txtDinheiroActionPerformed

    private void lblNmr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNmr1MouseClicked
        // TODO add your handling code here:
        if ((dinheiro >= valor[0]) && !(lblValor1.getText().equals(""))) {
            movimento(lblQuadro1);
            troco = dinheiro - valor[0];
            lblValor1.setText("");
         
            saidaProd();
        } else {
            JOptionPane.showMessageDialog(null, "Dinheiro insuficiente ou valor do produto não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_lblNmr1MouseClicked

    private void lblNmr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNmr2MouseClicked
       
        // TODO add your handling code here:
        if ((dinheiro >= valor[1]) && !(lblValor2.getText().equals(""))) {
            movimento(lblQuadro2);
            troco = dinheiro - valor[1];
            lblValor2.setText("");
            saidaProd();
        } else {
            JOptionPane.showMessageDialog(null, "Dinheiro insuficiente ou valor do produto não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_lblNmr2MouseClicked

    private void lblQuadroSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuadroSaidaMouseClicked
        // TODO add your handling code here:
        lblQuadroSaida.setIcon(null);
        lblVisor.setText("VISOR");
        lblTroco.setText("TROCO");
        txtDinheiro.setText(null);
        CarregaLabels();
    }//GEN-LAST:event_lblQuadroSaidaMouseClicked

    private void lblNmr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNmr3MouseClicked
        // TODO add your handling code here:
        if ((dinheiro >= valor[2]) && !(lblValor3.getText().equals(""))) {
            movimento(lblQuadro3);
            troco = dinheiro - valor[2];
            lblValor3.setText("");

            saidaProd();
        } else {
           JOptionPane.showMessageDialog(null, "Dinheiro insuficiente ou valor do produto não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_lblNmr3MouseClicked

    private void lblNmr4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNmr4MouseClicked
        // TODO add your handling code here:
        if ((dinheiro >= valor[3]) && !(lblValor4.getText().equals(""))) {
            movimento(lblQuadro4);
            troco = dinheiro - valor[3];
            lblValor4.setText("");
            saidaProd();
        } else {
           JOptionPane.showMessageDialog(null, "Dinheiro insuficiente ou valor do produto não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_lblNmr4MouseClicked

    private void lblNmr5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNmr5MouseClicked
        // TODO add your handling code here:
        if ((dinheiro >= valor[4]) && !(lblValor5.getText().equals(""))) {
            movimento(lblQuadro5);
            troco = dinheiro - valor[4];
            lblValor5.setText("");
            saidaProd();
        } else {
            JOptionPane.showMessageDialog(null, "Dinheiro insuficiente ou valor do produto não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_lblNmr5MouseClicked

    private void lblNmr6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNmr6MouseClicked
        // TODO add your handling code here:
        if ((dinheiro >= valor[5]) && !(lblValor6.getText().equals(""))) {
            movimento(lblQuadro6);
            troco = dinheiro - valor[5];
            lblValor6.setText("");
            saidaProd();
        } else {
          JOptionPane.showMessageDialog(null, "Dinheiro insuficiente ou valor do produto não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_lblNmr6MouseClicked

    private void lblNmr7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNmr7MouseClicked
        // TODO add your handling code here:
        if ((dinheiro >= valor[6]) && !(lblValor7.getText().equals(""))) {
            movimento(lblQuadro7);
            troco = dinheiro - valor[6];
            lblValor7.setText("");
            saidaProd();
        } else {
            JOptionPane.showMessageDialog(null, "Dinheiro insuficiente ou valor do produto não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_lblNmr7MouseClicked

    private void lblNmr8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNmr8MouseClicked
        // TODO add your handling code here:
        if ((dinheiro >= valor[7]) && !(lblValor8.getText().equals(""))) {
            movimento(lblQuadro8);
            troco = dinheiro - valor[7];
            lblValor8.setText("");

            saidaProd();
        } else {
            JOptionPane.showMessageDialog(null, "Dinheiro insuficiente ou valor do produto não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_lblNmr8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelCenter;
    private javax.swing.JPanel JPanelMachine;
    private javax.swing.JPanel JPanelMachineVisor;
    private javax.swing.JPanel JPanelQuadro;
    private javax.swing.JLabel lblDinheiro10;
    private javax.swing.JLabel lblDinheiro2;
    private javax.swing.JLabel lblDinheiro5;
    private javax.swing.JLabel lblNmr1;
    private javax.swing.JLabel lblNmr2;
    private javax.swing.JLabel lblNmr3;
    private javax.swing.JLabel lblNmr4;
    private javax.swing.JLabel lblNmr5;
    private javax.swing.JLabel lblNmr6;
    private javax.swing.JLabel lblNmr7;
    private javax.swing.JLabel lblNmr8;
    private javax.swing.JLabel lblNmr9;
    private javax.swing.JLabel lblQuadro1;
    private javax.swing.JLabel lblQuadro2;
    private javax.swing.JLabel lblQuadro3;
    private javax.swing.JLabel lblQuadro4;
    private javax.swing.JLabel lblQuadro5;
    private javax.swing.JLabel lblQuadro6;
    private javax.swing.JLabel lblQuadro7;
    private javax.swing.JLabel lblQuadro8;
    private javax.swing.JLabel lblQuadro9;
    private javax.swing.JLabel lblQuadroSaida;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JLabel lblValor4;
    private javax.swing.JLabel lblValor5;
    private javax.swing.JLabel lblValor6;
    private javax.swing.JLabel lblValor7;
    private javax.swing.JLabel lblValor8;
    private javax.swing.JLabel lblValor9;
    private javax.swing.JLabel lblVisor;
    private javax.swing.JTextField txtDinheiro;
    // End of variables declaration//GEN-END:variables

    private void fotoNota2() {
        ImageIcon urna = new ImageIcon("D:\\Projetos Completos\\Projeto Machine Candy\\Machine Candy\\src\\com\\machine\\img\\Nota2.jpg");
        Image image = urna.getImage();
        Image scaledImage = image.getScaledInstance(lblDinheiro2.getWidth(), lblDinheiro2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        lblDinheiro2.setIcon(scaledIcon);
    }

    private void fotoNota5() {
        ImageIcon adm = new ImageIcon("D:\\Projetos Completos\\Projeto Machine Candy\\Machine Candy\\src\\com\\machine\\img\\Nota5.jpg");
        Image image = adm.getImage();
        Image scaledImage = image.getScaledInstance(lblDinheiro5.getWidth(), lblDinheiro5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        lblDinheiro5.setIcon(scaledIcon);
    }

    private void fotoNota10() {
        ImageIcon adm = new ImageIcon("D:\\Projetos Completos\\Projeto Machine Candy\\Machine Candy\\src\\com\\machine\\img\\Nota10.jpg");
        Image image = adm.getImage();
        Image scaledImage = image.getScaledInstance(lblDinheiro10.getWidth(), lblDinheiro10.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        lblDinheiro10.setIcon(scaledIcon);
    }
}
